import { RootState } from "../reducers";

export const GET_SHOP_REQUEST = "GET_SHOP_REQUEST";
export const GET_SHOP_SUCCESS = "GET_SHOP_SUCCESS";
export const GET_SHOP_FAILURE = "GET_SHOP_FAILURE";

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";

export const GET_SHOPBYID_REQUEST = "GET_SHOPBYID_REQUEST";
export const GET_SHOPBYID_SUCCESS = "GET_SHOPBYID_SUCCESS";
export const GET_SHOPBYID_FAILURE = "GET_SHOPBYID_FAILURE";

export const GET_SHOPBYCATEGORY_REQUEST = "GET_SHOPBYCATEGORY_REQUEST";
export const GET_SHOPBYCATEGORY_SUCCESS = "GET_SHOPBYCATEGORY_SUCCESS";
export const GET_SHOPBYCATEGORY_FAILURE = "GET_SHOPBYCATEGORY_FAILURE";
